apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskazure
  labels:
    app-azure: flaskazure
spec:
  selector:
    matchLabels:
      app: flaskazure
  replicas: 2
  template:
    metadata:
      labels:
        app: flaskazure
    spec:
      containers:
      - name: flaskazure
        image: julio0619/flaskazure
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
