apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: Ingress
  labels:
    name: Ingress
spec:
  rules:
  - host: nsflask.duckdns.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: flaskazure
            port: 
              number: 8080
